# Generated by Django 3.1.7 on 2021-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=250, verbose_name='Назва')),
                ('price_product', models.IntegerField(verbose_name='Ціна')),
                ('about_product', models.TextField(verbose_name='Опис')),
                ('date', models.DateTimeField(verbose_name='Дата добавлення')),
            ],
        ),
    ]
