# Generated by Django 3.1.7 on 2021-05-09 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавлення'),
        ),
    ]
