# Generated by Django 3.1.7 on 2021-05-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210227_1820'),
        ('mainpage', '0002_products_date1'),
    ]

    operations = [
    ]
