# Generated by Django 3.1.7 on 2021-05-10 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_merge_20210509_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date1',
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавлення'),
        ),
    ]
